<a href="https://colab.research.google.com/github/hsrkl/techrush26/blob/notebooks/FF_detection_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix
from imblearn.over_sampling import SMOTE
from datasets import load_dataset

In [ ]:
path = kagglehub.dataset_download("ealaxi/paysim1")
df = pd.read_csv(os.path.join(path, "PS_20174392719_1491204439457_log.csv"))
df.drop(columns=['isFlaggedFraud'], inplace=True)

In [ ]:
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0

In [ ]:
print(df[df['nameDest'].str.startswith('M') & ((df['oldbalanceDest'] != 0) | (df['newbalanceDest'] != 0))].shape) # empty :D
customer_df = df[df['nameDest'].str.startswith('C')]
merchant_df = df[df['nameDest'].str.startswith('M')]

print((merchant_df['isFraud'] == 1).sum())

(0, 10)
0

In [ ]:
senders = set(df['nameOrig'])
receivers = set(df['nameDest'])

chain_accounts = senders.intersection(receivers)
print(f"Accounts that appear as both sender and receiver: {len(chain_accounts)}")

Accounts that appear as both sender and receiver: 1769

In [ ]:
df['errorBalanceOrig'] = df['newbalanceOrig'] - df['oldbalanceOrg'] + df['amount']
df['errorBalanceDest'] = df['oldbalanceDest'] - df['newbalanceDest'] + df['amount']

df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,errorBalanceOrig,errorBalanceDest
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0.00,9839.64
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0.00,1864.28
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0.00,181.00
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0.00,21363.00
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0.00,11668.14
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0.00,7817.71
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0.00,7107.77
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0.00,7861.64
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,1353.36,4024.36
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0.00,6886.98

In [ ]:
def find_real(df, tolerance):
    return df[(df['errorBalanceOrig'].abs() < tolerance) & (df['errorBalanceDest'].abs() < tolerance)]

intersection = find_real(df, 0.1) #the ones where there is no discrepancy are basically all sent to customers, merchants always have error cause old/new dest balance is zero
print(intersection.shape)

#intx_customer = find_real(customer_df, 0.1) # approx equal to intersection, off by 8
#print(intx_customer.shape)

#intx_merch = df[df['nameDest'].str.startswith('M') & (df['errorBalanceOrig'].abs() < 0.1)]
#print(intx_merch.shape)

(279810, 12)

In [ ]:
print(intersection['isFraud'].value_counts()) # 275k non-fraud, 3.9k fraud

#print(df['isFraud'].value_counts())
#print(intx_customer['isFraud'].value_counts())

isFraud
0    275857
1      3953
Name: count, dtype: int64

In [ ]:
intersection.head(50)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,errorBalanceOrig,errorBalanceDest
1124,1,DEBIT,6765.12,C67620673,50317.00,43551.88,C1122805102,16803.80,23568.91,0,0.000000e+00,1.000000e-02
1169,1,CASH_OUT,9980.32,C1589466857,12936.00,2955.68,C1018298342,0.00,9980.32,0,0.000000e+00,0.000000e+00
1171,1,DEBIT,2763.95,C458817438,60249.00,57485.05,C846947180,10137.14,12901.08,0,0.000000e+00,1.000000e-02
1426,1,DEBIT,3014.72,C1987354705,31568.00,28553.28,C40075281,25407.65,28422.37,0,0.000000e+00,3.637979e-12
1450,1,TRANSFER,40149.38,C428245792,287443.90,247294.52,C1291286504,26426.12,66575.50,0,-5.820766e-11,0.000000e+00
1478,1,DEBIT,5454.05,C470132045,86214.00,80759.95,C1330106945,18590.13,24044.18,0,0.000000e+00,0.000000e+00
1681,1,DEBIT,3548.72,C1596144422,12427.00,8878.28,C564742142,13271.31,16820.03,0,0.000000e+00,0.000000e+00
1746,1,DEBIT,6159.72,C810262298,24815.00,18655.28,C1321640594,12751.13,18910.85,0,0.000000e+00,0.000000e+00
1755,1,DEBIT,1533.55,C2134915053,45093.00,43559.45,C75457651,29936.24,31469.78,0,0.000000e+00,1.000000e-02
1756,1,DEBIT,3256.43,C619241052,10935.00,7678.57,C1292838001,26222.91,29479.34,0,0.000000e+00,0.000000e+00
1813,1,TRANSFER,27008.84,C2002097394,5292599.20,5265590.36,C824009085,37097.33,64106.18,0,0.000000e+00,-1.000000e-02
1829,1,DEBIT,642.26,C1884422865,21363.00,20720.74,C1509514333,1772.90,2415.16,0,0.000000e+00,0.000000e+00
1870,1,CASH_OUT,25071.46,C1275464847,25071.46,0.00,C1364913072,9083.76,34155.22,1,0.000000e+00,0.000000e+00
1978,1,DEBIT,4479.63,C1418851979,154215.60,149735.97,C339924917,7666.22,12145.85,0,0.000000e+00,0.000000e+00
2104,1,DEBIT,3870.28,C409596180,317403.38,313533.10,C24119573,6519.30,10389.58,0,0.000000e+00,0.000000e+00
2110,1,DEBIT,454.51,C199150625,30818.00,30363.49,C13226198,916.00,1370.51,0,0.000000e+00,0.000000e+00
2125,1,TRANSFER,22190.99,C2017380745,52231.01,30040.03,C1170794006,0.00,22190.99,0,1.000000e-02,0.000000e+00
2193,1,CASH_OUT,218499.73,C1788256184,359257.15,140757.42,C392292416,3201603.35,3420103.09,0,0.000000e+00,-1.000000e-02
2194,1,CASH_OUT,107440.87,C128028301,140757.42,33316.54,C423583818,266398.11,373838.99,0,-1.000000e-02,-1.000000e-02
2202,1,DEBIT,8972.41,C1573125303,331601.00,322628.59,C747464370,1558462.41,1567434.81,0,0.000000e+00,1.000000e-02
2212,1,DEBIT,4448.09,C810169941,8739.69,4291.60,C1259769769,247607.16,252055.24,0,0.000000e+00,1.000000e-02
2229,1,DEBIT,930.99,C2017393480,18354.65,17423.66,C1032986144,17230.80,18161.79,0,0.000000e+00,0.000000e+00
2294,1,DEBIT,286.87,C1632300236,3014.00,2727.13,C1504109395,593450.51,593737.38,0,0.000000e+00,0.000000e+00
2300,1,DEBIT,452.57,C1199833406,62396.00,61943.43,C1529115495,66815.45,67268.02,0,0.000000e+00,0.000000e+00
2302,1,CASH_OUT,235238.66,C1499825229,235238.66,0.00,C2100440237,0.00,235238.66,1,0.000000e+00,0.000000e+00
2328,1,CASH_OUT,153596.45,C979532928,711133.71,557537.26,C1360767589,1954368.93,2107965.39,0,0.000000e+00,-1.000000e-02
2350,1,CASH_OUT,462688.96,C1955587357,2055866.56,1593177.60,C11003494,10126196.31,10588885.27,0,0.000000e+00,1.862645e-09
2351,1,CASH_OUT,75915.44,C1095849663,1593177.60,1517262.16,C1234250905,117103.50,193018.94,0,-2.328306e-10,0.000000e+00
2378,1,TRANSFER,15326.30,C353296011,105867.00,90540.70,C1182908789,0.00,15326.30,0,0.000000e+00,0.000000e+00
2446,1,DEBIT,2983.50,C1440939580,19727.26,16743.76,C1810132623,97128.19,100111.69,0,0.000000e+00,0.000000e+00
2559,1,DEBIT,4188.03,C722513129,8765.00,4576.97,C101601906,16097.76,20285.79,0,0.000000e+00,0.000000e+00
2575,1,DEBIT,8326.13,C1595354442,25675.00,17348.87,C1058634310,16727.60,25053.73,0,0.000000e+00,-3.637979e-12
2596,1,DEBIT,525.22,C1431699407,10229.00,9703.78,C1034584766,1003.00,1528.22,0,0.000000e+00,0.000000e+00
2805,2,DEBIT,3718.70,C792195577,20793.00,17074.30,C1041638599,13785.78,17504.47,0,0.000000e+00,1.000000e-02
2857,2,DEBIT,2307.17,C304966690,15629.00,13321.83,C884457408,82609.64,84916.82,0,0.000000e+00,-1.000000e-02
2890,2,DEBIT,677.53,C2095793272,37067.00,36389.47,C925936450,9376.00,10053.53,0,0.000000e+00,0.000000e+00
2960,2,DEBIT,7257.37,C74735260,32516.91,25259.53,C1761291320,22233.65,29491.02,0,-1.000000e-02,0.000000e+00
3006,2,DEBIT,3882.80,C890060621,15135.00,11252.20,C1018298342,9980.32,13863.12,0,0.000000e+00,-1.818989e-12
3009,2,CASH_OUT,9255.25,C1177852821,35391.39,26136.14,C1941598182,38668.08,47923.33,0,0.000000e+00,0.000000e+00
3033,2,DEBIT,3462.64,C1623761043,66331.00,62868.36,C2094777811,64259.52,67722.17,0,0.000000e+00,-1.000000e-02
3060,2,CASH_OUT,1096187.24,C77163673,1096187.24,0.00,C644345897,0.00,1096187.24,1,0.000000e+00,0.000000e+00
3067,2,DEBIT,1890.03,C558913557,39670.00,37779.97,C977993101,742374.93,744264.96,0,0.000000e+00,1.164153e-10
3071,2,DEBIT,2307.78,C324158286,219948.76,217640.98,C566698125,22876.00,25183.78,0,0.000000e+00,0.000000e+00
3072,2,CASH_OUT,97601.12,C1335520301,217640.98,120039.86,C2081595126,99684.00,197285.12,0,-2.910383e-11,0.000000e+00
3100,2,DEBIT,1654.94,C737897289,146980.00,145325.06,C77811359,11147.00,12801.94,0,0.000000e+00,0.000000e+00
3149,2,DEBIT,1053.29,C501855493,11687.00,10633.71,C270095066,16267.62,17320.91,0,0.000000e+00,0.000000e+00
3152,2,DEBIT,7481.76,C932118570,41487.00,34005.24,C297927961,90508.53,97990.29,0,0.000000e+00,0.000000e+00
3157,2,DEBIT,6408.60,C1964514128,25457.00,19048.40,C1917025677,42900.67,49309.27,0,0.000000e+00,0.000000e+00
3163,2,CASH_OUT,963532.14,C430329518,963532.14,0.00,C991505714,132382.57,1095914.71,1,0.000000e+00,0.000000e+00
3168,2,DEBIT,633.34,C1185575212,24065.00,23431.66,C461160828,17860.54,18493.88,0,0.000000e+00,0.000000e+00